name: CI/CD Pipeline

on:
    push:
        branches: ['main']

    workflow_dispatch:

jobs:
    build:
        uses: ./.github/workflows/build.yml

    deploy_to_github_pages:
        needs: build
        # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
        permissions:
            pages: write
            id-token: write
        uses: ./.github/workflows/deploy_to_github_pages.yml
