name: CI/CD Pipeline

on:
    push:
        branches: ['main']

    workflow_dispatch:

jobs:
    provision:
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/provision.yml

    build:
        uses: ./.github/workflows/build.yml

    deploy_to_s3:
        needs: [provision, build]
        permissions:
            id-token: write
        uses: ./.github/workflows/deploy_to_s3.yml

    deploy_to_github_pages:
        needs: build
        permissions:
            pages: write
            id-token: write
        uses: ./.github/workflows/deploy_to_github_pages.yml
