name: Provision

on:
    workflow_call:

jobs:
    provision:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials using OIDC
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-region: us-east-1
                  role-to-assume: arn:aws:iam::574783120239:role/github-actions-oidc-role

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Initialize Terraform
              run: terraform init
              working-directory: ./terraform

            - name: Plan Terraform
              run: terraform plan -out=tfplan
              working-directory: ./terraform

            - name: Apply Terraform
              run: terraform apply -auto-approve tfplan
              working-directory: ./terraform
